### ISSUE TITLE
Pin Rules Engine to exact version

### ISSUE THREAD

**Issue by timsearle** [adobe/aepsdk-target-ios#114]
### Expected Behaviour
All dependencies for a given version of the Target package are pinned to exact versions

### Actual Behaviour
https://github.com/adobe/aepsdk-rulesengine-ios.git is set to `upToNextMajor` in `Package.swift` - this means SPM in Xcode is more likely to regularly re-resolve packages and can mean what gets built on CI is different to what has been built locally.

#### Sample Code that illustrates the problem
https://github.com/adobe/aepsdk-target-ios/blob/d78737f8fc24965d385ced2efd2ba9fabb22348b/Package.swift#L23

Change to:

```swift
.package(url: "https://github.com/adobe/aepsdk-core-ios.git", .exact("3.1.0")),
```

**Comment by praveek** [comment]
@timsearle Please commit `Packages.resolved` to your repository to lock in specific version of the dependencies. Changing it to `.exact` is not possible as the app can include multiple extensions depending on `aepsdk-core-ios`.

**Comment by timsearle** [comment]
Apologies - I referenced the wrong package, I meant to reference this one:

https://github.com/adobe/aepsdk-core-ios/blob/1f037918856101e863a8e6b1bc44e04ca40f189f/Package.swift#L29

We do have our Package.resolved committed, but Xcode's integration with SPM seems to often re-generate/update it with these downstream package resolutions to higher versions.
