### ISSUE TITLE
Add xcframeworks to release

### ISSUE THREAD

**Issue by kunal30xi** [adobe/aepsdk-target-ios#139]
Now that aepsdk-core-ios and aepsdk-assurance-ios are both making XCframeworks available with their latest release (4.0.0), can we ensure that XCFramework binaries are released for target as well?

**Comment by addb** [comment]
Hey @kunal30xi, we will be releasing Target 4.0.0 with the XCFrameworks really soon (this week).

Thanks,
Arjun
